name: inventory_management_api

services:
  db:
    image: postgres:15
    container_name: db
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db-data:
