# Generated by Django 5.1.4 on 2024-12-16 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_rename_categories_products_category_ids"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="category_ids",
            new_name="categories",
        ),
        migrations.RenameField(
            model_name="products",
            old_name="unit_id",
            new_name="unit",
        ),
    ]
