# Generated by Django 5.1.4 on 2024-12-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_rename_category_ids_products_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name="products",
            name="retail_price",
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
