# Generated by Django 5.1.4 on 2024-12-14 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="users",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="users",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="users",
            name="username",
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator(
                        message="Enter a valid email address."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="first_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="users",
            name="phone_number",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 13 digits allowed.",  # noqa E501
                        regex="^\\+?1?\\d{9,13}$",
                    )
                ],
            ),
        ),
    ]
