name: Pre-Commit Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # Step 3: Update and install system dependencies
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends pipx
          export PATH="/root/.local/bin:$PATH"
          pipx install poetry
          pipx install pre-commit

      # Step 4: Install project dependencies with Poetry
      - name: Install Python Dependencies with Poetry
        run: |
          poetry install

      # Step 5: Activate Poetry virtual environment and run pre-commit
      - name: Run Pre-Commit
        run: |
          source $(poetry env info --path)/bin/activate
          pre-commit run --all-files
